window.TOPICS = {
  1: { title: 'Базовые правила',
       ruleUrl: '/rules/0.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/0.html" loading="lazy"></iframe>' },
  1: { title: 'Н и НН в суффиксах',
       ruleUrl: '/rules/1.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/1.html" loading="lazy"></iframe>' },
  2: { title: 'Приставки ПРЕ- и ПРИ-',
       ruleUrl: '/rules/2.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/2.html" loading="lazy"></iframe>' },
  3: { title: 'Употребление НЕ и НИ',
       ruleUrl: '/rules/3.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/3.html" loading="lazy"></iframe>' },
  4: { title: 'Приставки ПОЛ- и ПОЛУ-',
       ruleUrl: '/rules/4.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/4.html" loading="lazy"></iframe>' },
  5: { title: 'Дефис: правила и особенности',
       ruleUrl: '/rules/5.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/5.html" loading="lazy"></iframe>' },
  6: { title: 'Правописание Ы и И',
       ruleUrl: '/rules/6.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/6.html" loading="lazy"></iframe>' },
  7: { title: 'Правописание слов с Ь и без',
       ruleUrl: '/rules/7.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/7.html" loading="lazy"></iframe>' },
  8: { title: 'Выбор между Ь и Ъ',
       ruleUrl: '/rules/8.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/8.html" loading="lazy"></iframe>' },
  9: { title: 'Чередование А/О, И/Е',
       ruleUrl: '/rules/9.html',
       ruleHtml: '<iframe class="rule-frame" src="rules/9.html" loading="lazy"></iframe>' },
  10: { title: 'О и Ё после шипящих и Ц',
        ruleUrl: '/rules/10.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/10.html" loading="lazy"></iframe>' },
  11: { title: 'Трудные случаи с предлогами и наречиями',
        ruleUrl: '/rules/11.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/11.html" loading="lazy"></iframe>' },
  12: { title: 'Слова, в которых часто делают ошибки',
        ruleUrl: '/rules/12.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/12.html" loading="lazy"></iframe>' },
  13: { title: 'Аббревиатуры, сокращения и символы',
        ruleUrl: '/rules/13.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/13.html" loading="lazy"></iframe>' },
  14: { title: 'Правописание имен собственных и географических названий',
        ruleUrl: '/rules/14.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/14.html" loading="lazy"></iframe>' },
  15: { title: 'Трудные числительные',
        ruleUrl: '/rules/15.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/15.html" loading="lazy"></iframe>' },
  16: { title: 'Формы множественного числа',
        ruleUrl: '/rules/16.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/16.html" loading="lazy"></iframe>' },
  17: { title: 'Лексическая сочетаемость и выбор слов',
        ruleUrl: '/rules/17.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/17.html" loading="lazy"></iframe>' },
  18: { title: 'Орфоэпия и произношение',
        ruleUrl: '/rules/18.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/18.html" loading="lazy"></iframe>' },
  19: { title: 'Использование союза КАК',
        ruleUrl: '/rules/19.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/19.html" loading="lazy"></iframe>' },
  20: { title: 'Сложные случаи пунктуации',
        ruleUrl: '/rules/20.html',
        ruleHtml: '<iframe class="rule-frame" src="rules/20.html" loading="lazy"></iframe>' }
};
